import { useCallback, useEffect, useMemo, useState } from 'react';

const STATUS = { pending: 'Pendiente', paid: 'Pagado', shipped: 'Enviado', completed: 'Completado', cancelled: 'Cancelado' };
const money = (n, currency = 'RD$') => `${currency} ${Number(n || 0).toLocaleString('es-DO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

function ProductRows({ products, catalog, onChange, onRemove }) {
  const addProduct = (id) => { if (!id) return; const p = catalog.find((item) => item.id === id); if (!p) return; const existing = products.find((item) => item.productId === id); if (existing) onChange(products.map((item) => item.productId === id ? { ...item, quantity: item.quantity + 1, subtotal: (item.quantity + 1) * item.unitPrice } : item)); else onChange([...products, { productId: p.id, name: p.name, quantity: 1, unitPrice: Number(p.price) || 0, subtotal: Number(p.price) || 0 }]); };
  const update = (index, field, value) => onChange(products.map((item, i) => { if (i !== index) return item; const next = { ...item, [field]: field === 'quantity' ? Math.max(1, Math.floor(Number(value) || 1)) : Math.max(0, Number(value) || 0) }; next.subtotal = next.quantity * next.unitPrice; return next; }));
  return <div><div className="order-product-picker"><label>Agregar producto<select defaultValue="" onChange={(e) => { addProduct(e.target.value); e.target.value = ''; }}><option value="">Seleccionar producto…</option>{catalog.map((p) => <option key={p.id} value={p.id}>{p.name} — {money(p.price)}</option>)}</select></label></div>{products.length === 0 ? <div className="empty-state" style={{ padding: 20 }}><p>No hay productos en esta orden.</p></div> : <div className="order-product-lines">{products.map((item, index) => <div className="order-product-line" key={`${item.productId}-${index}`}><label>Producto<input value={item.name} readOnly /></label><label>Cantidad<input type="number" min="1" value={item.quantity} onChange={(e) => update(index, 'quantity', e.target.value)} /></label><label>Precio<input type="number" min="0" step="0.01" value={item.unitPrice} onChange={(e) => update(index, 'unitPrice', e.target.value)} /></label><label>Subtotal<input value={money(item.subtotal)} readOnly /></label><button type="button" className="icon-btn danger-icon" title="Eliminar producto" onClick={() => onRemove(index)}>✕</button></div>)}</div>}</div>;
}

export default function OrdersPanel({ adminToken, products: catalog, showToast }) {
  const [orders, setOrders] = useState([]); const [loading, setLoading] = useState(true); const [filter, setFilter] = useState('all'); const [search, setSearch] = useState(''); const [editing, setEditing] = useState(null); const [form, setForm] = useState(null); const [loadError, setLoadError] = useState('');
  const headers = useMemo(() => ({ Authorization: `Bearer ${adminToken}`, 'Content-Type': 'application/json' }), [adminToken]);
  const load = useCallback(async () => { setLoading(true); setLoadError(''); try { const r = await fetch('/api/orders', { headers }); const data = await r.json().catch(() => ({})); if (!r.ok) { const error = data.error || ''; if (error === 'ADMIN_NOT_CONFIGURED') throw new Error('La cuenta de administrador aún no está configurada.'); throw new Error(data.message || error || 'No se pudieron cargar las órdenes.'); } setOrders(data.orders || []); } catch (e) { setLoadError(e.message); showToast(e.message); } finally { setLoading(false); } }, [headers, showToast]);
  useEffect(() => { load(); }, [load]);
  const today = new Date().toISOString().slice(0, 10); const todayOrders = orders.filter((o) => String(o.createdAt || '').slice(0, 10) === today); const revenueToday = todayOrders.reduce((s, o) => s + Number(o.total || 0), 0); const pending = orders.filter((o) => o.status === 'pending').length;
  const visible = orders.filter((o) => { const q = search.trim().toLowerCase(); const haystack = `${o.id || ''} ${o.customerName || ''} ${o.phone || ''} ${(o.products || []).map((p) => p.name).join(' ')}`.toLowerCase(); return (filter === 'all' || o.status === filter) && (!q || haystack.includes(q)); });
  const startNew = () => { setEditing('new'); setForm({ customerName: '', phone: '', notes: '', status: 'pending', products: [] }); };
  const startEdit = (order) => { setEditing(order.id); setForm({ customerName: order.customerName || '', phone: order.phone || '', notes: order.notes || '', status: order.status || 'pending', products: (order.products || []).map((p) => ({ ...p })) }); };
  const save = async () => { if (!form.customerName.trim()) return showToast('El nombre del cliente es obligatorio.'); if (!form.products.length) return showToast('Agrega al menos un producto.'); const method = editing === 'new' ? 'POST' : 'PUT'; const body = editing === 'new' ? form : { ...form, id: editing }; try { const r = await fetch('/api/orders', { method, headers, body: JSON.stringify(body) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.message || data.error || 'No se pudo guardar la orden.'); showToast(editing === 'new' ? 'Orden creada' : 'Orden actualizada'); setEditing(null); setForm(null); await load(); } catch (e) { showToast(e.message); } };
  const remove = async (id) => { if (!confirm('¿Eliminar esta orden?')) return; try { const r = await fetch('/api/orders', { method: 'DELETE', headers, body: JSON.stringify({ id }) }); if (!r.ok) throw new Error('No se pudo eliminar la orden.'); showToast('Orden eliminada'); await load(); } catch (e) { showToast(e.message); } };
  const quickStatus = async (order, status) => { try { const r = await fetch('/api/orders', { method: 'PUT', headers, body: JSON.stringify({ id: order.id, status }) }); if (!r.ok) throw new Error('No se pudo actualizar el estado.'); await load(); } catch (e) { showToast(e.message); } };

  if (editing && form) { const total = form.products.reduce((s, p) => s + Number(p.quantity || 0) * Number(p.unitPrice || 0), 0); return <div><div className="panel-head"><div><span className="section-kicker">ÓRDENES</span><h2>{editing === 'new' ? 'Nueva orden' : 'Editar orden'}</h2></div><button className="icon-btn" onClick={() => { setEditing(null); setForm(null); }}>✕</button></div><div className="form-grid"><label>Cliente<input value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value })} /></label><label>WhatsApp<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} inputMode="tel" /></label><label>Estado<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{Object.entries(STATUS).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label><label>Notas<textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><h3 className="subsection-title">Productos</h3><ProductRows products={form.products} catalog={catalog} onChange={(products) => setForm({ ...form, products })} onRemove={(index) => setForm({ ...form, products: form.products.filter((_, i) => i !== index) })} /><div className="cart-total-row order-total"><span>Total</span><strong className="mono">{money(total)}</strong></div><div className="form-actions"><button className="btn-secondary" onClick={() => { setEditing(null); setForm(null); }}>Cancelar</button><button className="btn-primary" onClick={save}>Guardar orden</button></div></div>; }

  return <div className="orders-panel"><div className="panel-head"><div><span className="section-kicker">GESTIÓN</span><h2>Órdenes</h2><p className="admin-subtitle">Gestiona pedidos recibidos y órdenes creadas manualmente.</p></div><button className="btn-primary" onClick={startNew}>+ Nueva orden</button></div>
    <div className="orders-stats"><div className="stat-card"><span>Órdenes hoy</span><strong>{todayOrders.length}</strong></div><div className="stat-card"><span>Ingresos hoy</span><strong>{money(revenueToday)}</strong></div><div className="stat-card"><span>Pendientes</span><strong>{pending}</strong></div><div className="stat-card"><span>Total órdenes</span><strong>{orders.length}</strong></div></div>
    <div className="orders-toolbar"><div className="orders-search"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por cliente, teléfono, orden o producto…"/><button type="button" className="search-clear" onClick={() => setSearch('')} style={{ visibility: search ? 'visible' : 'hidden' }}>✕</button></div><select className="order-filter" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">Todos los estados</option>{Object.entries(STATUS).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select><button className="btn-secondary refresh-btn" onClick={load}>↻ Actualizar</button></div>
    {loadError ? <div className="orders-error"><div className="error-icon">!</div><h3>Órdenes no disponibles</h3><p>{loadError}</p><button className="btn-secondary" onClick={load}>Reintentar</button></div> : loading ? <div className="empty-state" style={{ padding: 30 }}><p>Cargando órdenes…</p></div> : visible.length === 0 ? <div className="empty-state orders-empty"><div className="glyph">📦</div><h3>{search ? 'No encontramos resultados' : 'No hay órdenes'}</h3><p>{search ? 'Prueba con otro término de búsqueda.' : 'Las nuevas órdenes aparecerán aquí.'}</p></div> : <div className="orders-table-wrap"><table className="orders-table"><thead><tr>{['Orden','Cliente','Productos','Total','Estado','Fecha',''].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map((order) => <tr key={order.id}><td className="mono order-id">#{order.id.slice(-8)}</td><td><strong>{order.customerName}</strong><small>{order.phone}</small></td><td className="order-products-cell">{(order.products || []).map((p) => `${p.name} ×${p.quantity}`).join(', ')}</td><td className="mono"><strong>{money(order.total)}</strong></td><td><select className={`status-select status-${order.status}`} value={order.status} onChange={(e) => quickStatus(order, e.target.value)}>{Object.entries(STATUS).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></td><td className="order-date">{new Date(order.createdAt).toLocaleString('es-DO')}</td><td className="order-actions"><button className="btn-secondary" onClick={() => startEdit(order)}>Editar</button><button className="icon-btn danger-icon" onClick={() => remove(order.id)} title="Eliminar">🗑️</button></td></tr>)}</tbody></table></div>}
  </div>;
}
